//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_KhoaLa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.Saches = new HashSet<Sach>();
            HinhAnh = "~/Content/imgsach/add.png";
        }
        [DisplayName("Mã Đầu Sách:")]
        [Required(ErrorMessage = "Vui Lòng nhập Mã sách!")]
        public int MaDauSach { get; set; }

        [DisplayName("Tên Sách:")]
        //[Required(ErrorMessage = "Vui Lòng nhập tên sách!")]
        public string TenSach { get; set; }

        [DisplayName("Tên tác giả:")]
        //[Required(ErrorMessage = "Vui Lòng nhập tác giả sách!")]
        public string TacGia { get; set; }

        [DisplayName("Thể loại sách:")]
        //[Required(ErrorMessage = "Vui Lòng nhập thể loại sách!")]
        public string TheLoai { get; set; }

        [DisplayName("Năm xuất bản:")]
        //[Required(ErrorMessage = "Vui Lòng nhập năm xuất bản sách!")]
        public Nullable<int> NamXuatBan { get; set; }

        //[Required(ErrorMessage = "Vui Lòng nhập nhà xuất bản sách!")]
        [DisplayName("Nhà xuất bản:")]
        public string NhaXuatBan { get; set; }


        [DisplayName("link hình ảnh:")]
        public string HinhAnh { get; set; }

        [NotMapped]
        public HttpPostedFileBase imageUploader { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
