//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_KhoaLa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TheThuVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheThuVien()
        {
            this.DKyMuonSaches = new HashSet<DKyMuonSach>();
            this.Sach_Dang_Muon = new HashSet<Sach_Dang_Muon>();
        }

        [DisplayName("Mã thẻ:")]
        //[Required(ErrorMessage = "Vui Lòng nhập mã thẻ!")]
        public string MaThe { get; set; }

        [DisplayName("Mã tinh trạng:")]
        //[Required(ErrorMessage = "Vui Lòng nhập mã tinh trạng cho thẻ!")]
        public Nullable<int> MaTinhTrang { get; set; }

        [DisplayName("Mật Khẩu:")]
        //[Required(ErrorMessage = "Vui Lòng nhập mật khẩu!")]
        public string Password { get; set; }

        [DisplayName("Họ và tên:")]
        //[Required(ErrorMessage = "Vui Lòng nhập họ và tên chủ thẻ!")]
        public string HoTen { get; set; }

        [DisplayName("Ngày làm:")]
        //[Required(ErrorMessage = "Vui Lòng nhập ngày làm!")]
        public Nullable<System.DateTime> NgayLam { get; set; }

        [DisplayName("Ngày hết hạn:")]
        //[Required(ErrorMessage = "Vui Lòng nhập ngay hêt hạn!")]
        public Nullable<System.DateTime> NgayHetHan { get; set; }

        [DisplayName("Ghi chú:")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKyMuonSach> DKyMuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach_Dang_Muon> Sach_Dang_Muon { get; set; }
        public virtual TinhTrang_TheTV TinhTrang_TheTV { get; set; }
    }
}
