//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN1_QLTV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TheThuVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheThuVien()
        {
            this.DKyMuonSaches = new HashSet<DKyMuonSach>();
            this.Sach_Dang_Muon = new HashSet<Sach_Dang_Muon>();
        }

        [DisplayName("ID")]
        /*        [Required(ErrorMessage ="Không được bỏ trống!")]*/
        public string MaThe { get; set; }

        [DisplayName("Status")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public Nullable<int> MaTinhTrang { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        [MinLength(6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Họ Tên")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public string HoTen { get; set; }

        [DisplayName("Ngày làm thẻ")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public Nullable<System.DateTime> NgayLam { get; set; }

        [DisplayName("Ngày hết hạn")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public Nullable<System.DateTime> NgayHetHan { get; set; }

        [NotMapped]
        [Compare("Password")]
        [DisplayName("Nhập lại mật khẩu")]
        [DataType(DataType.Password)]

        /*        public bool Remember { get; set; }*/
        public string RePassword { get; set; }

        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKyMuonSach> DKyMuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach_Dang_Muon> Sach_Dang_Muon { get; set; }
        public virtual TinhTrang_TheTV TinhTrang_TheTV { get; set; }
    }
}
